tap "dashlane/tap"
brew "gmp"
brew "gh"
brew "git-delta"
brew "gitleaks"
brew "lazydocker"
brew "lazygit"
brew "libyaml"
brew "llvm"
brew "mas"
brew "mise"
brew "ncdu"
brew "redis", restart_service: :changed
brew "rust"
brew "tree"
brew "vips"
brew "wget"
brew "zsh-syntax-highlighting"
brew "dashlane/tap/dashlane-cli"
cask "affinity"
cask "appcleaner"
cask "balenaetcher"
cask "basecamp"
cask "cap"
cask "claude"
cask "claude-code"
cask "cyberduck"
cask "deepl"
cask "docker-desktop"
cask "dropbox"
cask "figma"
cask "firefox"
cask "firefox@developer-edition"
cask "font-red-hat-display"
cask "gimp"
cask "gitkraken"
cask "google-chrome"
cask "google-drive"
cask "handy"
cask "hey-desktop"
cask "inkscape"
cask "kdrive"
cask "languagetool-desktop"
cask "latest"
cask "ledger-wallet"
cask "linear-linear"
cask "mark-text"
cask "notion"
cask "nucleo"
cask "onlyoffice"
cask "postman"
cask "raindropio"
cask "raycast"
cask "reader"
cask "rectangle"
cask "responsively"
cask "signal"
cask "spotify"
cask "sublime-text"
cask "superwhisper"
cask "tableplus"
cask "timescribe"
cask "transmit"
cask "vlc"
cask "wailbrew"
cask "wakatime"
cask "zed"
mas "Dashlane", id: 517914548
mas "GarageBand", id: 682658836
mas "Hotspot Shield", id: 771076721
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "OomlIO", id: 6756478856
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "Slack", id: 803453959
mas "Telegram Lite", id: 946399090
